[package]
name = "model"
version = "1.0.0"
publish = false
edition = "2021"

[lib]
name = "model"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
proc-macros = { workspace = true }
near-sdk = { workspace = true }
